[package]
name = "fcp_routing"
version = "0.1.0"
authors = ["Valentin Lorentz <progval+git@progval.net>"]

[dependencies]
dht = { git = "https://github.com/rust-fcp/rust-dht.git", branch = "generic-address" }
rustc-serialize = "^0.3" # Required to implement dht::GenericId

[dev-dependencies]
fcp_cryptoauth = { git = "https://github.com/rust-fcp/rust-fcp-cryptoauth.git" }
fcp_switching = { git = "https://github.com/rust-fcp/rust-fcp-switching.git" }
hex = "*"
rand = "*"
