[package]
name = "fcp_routing"
version = "0.1.0"
authors = ["Valentin Lorentz <progval+git@progval.net>"]

[dependencies]
dht = "^0.0.5"
bencode = { git = "https://github.com/arjantop/rust-bencode.git" }
rustc-serialize = "^0.3"

[dev-dependencies]
fcp_cryptoauth = { git = "https://github.com/rust-fcp/rust-fcp-cryptoauth.git" }
fcp_switching = { git = "https://github.com/rust-fcp/rust-fcp-switching.git" }
hex = "*"
rand = "*"
